# Generated by Django 4.2.7 on 2024-12-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_google_access_token_customuser_google_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanofficerprofile',
            name='average_loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='loanofficerprofile',
            name='max_loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum preferred loan amount', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='loanofficerprofile',
            name='min_credit_score',
            field=models.IntegerField(blank=True, help_text='Minimum preferred credit score', null=True),
        ),
        migrations.AddField(
            model_name='loanofficerprofile',
            name='min_loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum preferred loan amount', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='loanofficerprofile',
            name='preferred_locations',
            field=models.JSONField(default=list, help_text='List of preferred locations (states/cities)'),
        ),
        migrations.AddField(
            model_name='loanofficerprofile',
            name='total_competitive_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loanofficerprofile',
            name='total_guaranteed_leads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loanofficerprofile',
            name='total_loans_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loanofficerprofile',
            name='success_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage of won loans vs total attempts', max_digits=5, null=True),
        ),
    ]
