# Generated by Django 4.2.7 on 2024-12-08 13:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_loanofficerprofile_average_loan_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanOfficerPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conventional_enabled', models.BooleanField(default=True)),
                ('fha_enabled', models.BooleanField(default=True)),
                ('va_enabled', models.BooleanField(default=True)),
                ('jumbo_enabled', models.BooleanField(default=True)),
                ('priority_loan_type', models.CharField(choices=[('conventional', 'Conventional'), ('fha', 'FHA'), ('va', 'VA'), ('jumbo', 'Jumbo')], default='conventional', max_length=20)),
                ('regions', models.JSONField(default=list)),
                ('open_to_all_regions', models.BooleanField(default=True)),
                ('min_loan_amount', models.DecimalField(decimal_places=2, default=100000, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_loan_amount', models.DecimalField(decimal_places=2, default=1000000, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_fico_score', models.IntegerField(default=620, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(850)])),
                ('max_fico_score', models.IntegerField(default=850, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(850)])),
                ('max_apr_threshold', models.DecimalField(decimal_places=2, default=7.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notify_guaranteed_loans', models.BooleanField(default=True)),
                ('notify_competitive_loans', models.BooleanField(default=True)),
                ('notify_bid_updates', models.BooleanField(default=True)),
                ('communicate_via_email', models.BooleanField(default=True)),
                ('communicate_via_sms', models.BooleanField(default=True)),
                ('communicate_via_dashboard', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_officer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='authentication.loanofficerprofile')),
            ],
            options={
                'verbose_name': 'Loan Officer Preferences',
                'verbose_name_plural': 'Loan Officer Preferences',
            },
        ),
    ]
