# Generated by Django 4.2.7 on 2024-12-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanofficerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loanofficerprofile',
            name='profile_completed',
            field=models.BooleanField(default=False, help_text='Whether the loan officer has completed their profile'),
        ),
    ]
