# Generated by Django 5.1.4 on 2024-12-10 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('OUTBID', 'Outbid'), ('BID_WON', 'Bid Won'), ('BID_LOST', 'Bid Lost'), ('LOAN_EXPIRED', 'Loan Expired'), ('NEW_LOAN', 'New Loan'), ('LOAN_STATUS_CHANGE', 'Loan Status Change'), ('LOAN_ASSIGNMENT', 'Loan Assignment')], max_length=20),
        ),
    ]
