# Generated by Django 5.1.4 on 2025-02-28 02:36

import document_processing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=document_processing.models.document_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('processing_errors', models.TextField(blank=True, null=True)),
                ('extracted_name', models.CharField(blank=True, max_length=255, null=True)),
                ('extracted_co_borrower_name', models.CharField(blank=True, max_length=255, null=True)),
                ('extracted_document_date', models.CharField(blank=True, max_length=20, null=True)),
                ('extracted_apr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('extracted_interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('extracted_loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('extracted_loan_term', models.IntegerField(blank=True, null=True)),
                ('extracted_loan_type', models.CharField(blank=True, max_length=50, null=True)),
                ('extracted_monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('extracted_monthly_mortgage_insurance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('extracted_monthly_escrow', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('extracted_closing_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('extracted_cash_to_close', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('extracted_loan_purpose', models.CharField(blank=True, max_length=50, null=True)),
                ('processing_time_ms', models.FloatField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('model_used', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
