# Generated by Django 5.1.4 on 2025-02-28 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processing', '0001_initial'),
        ('loans', '0002_loan_auto_assignment_attempts_loan_routing_priority_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadeddocument',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='created_loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_documents', to='loans.loan'),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='uploadeddocument',
            index=models.Index(fields=['uploaded_at'], name='document_pr_uploade_dad997_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadeddocument',
            index=models.Index(fields=['processed'], name='document_pr_process_182a85_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadeddocument',
            index=models.Index(fields=['uploaded_by'], name='document_pr_uploade_1b6e02_idx'),
        ),
    ]
