# Generated by Django 4.2.7 on 2024-12-08 00:51

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_apr', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('99.99'))])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('WINNING', 'Winning'), ('OUTBID', 'Outbid'), ('EXPIRED', 'Expired'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted')], default='PENDING', max_length=20)),
                ('is_lowest', models.BooleanField(default=False)),
                ('is_final', models.BooleanField(default=False)),
                ('rebid_count', models.IntegerField(default=0)),
                ('is_exclusive_bid', models.BooleanField(default=False)),
                ('competitive_bid_fee', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10)),
                ('proposed_term', models.IntegerField(blank=True, null=True)),
                ('proposed_monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bid',
                'verbose_name_plural': 'Bids',
                'ordering': ['bid_apr', '-created_at'],
            },
        ),
    ]
