# Generated by Django 4.2.7 on 2024-12-08 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bidding', '0001_initial'),
        ('loans', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='loans.loan'),
        ),
        migrations.AddField(
            model_name='bid',
            name='loan_officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='authentication.loanofficerprofile'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['loan', 'bid_apr'], name='bidding_bid_loan_id_37b731_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['loan_officer'], name='bidding_bid_loan_of_8d4531_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['status'], name='bidding_bid_status_4aca0e_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['created_at'], name='bidding_bid_created_759b40_idx'),
        ),
    ]
