# Generated by Django 4.2.7 on 2024-12-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='auto_assignment_attempts',
            field=models.IntegerField(default=0, help_text='Number of times the system attempted to auto-assign this loan'),
        ),
        migrations.AddField(
            model_name='loan',
            name='routing_priority',
            field=models.IntegerField(default=0, help_text='Priority score for guaranteed loan allocation'),
        ),
        migrations.AddField(
            model_name='loan',
            name='routing_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Score used for routing decisions', max_digits=5, null=True),
        ),
    ]
