# Generated by Django 5.1.4 on 2025-02-28 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loan_auto_assignment_attempts_loan_routing_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='last_notified_email',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='last_notified_sms',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='notify_by_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='notify_by_sms',
            field=models.BooleanField(default=True),
        ),
    ]
